# Generated by Django 4.2.2 on 2023-06-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyageherapi', '0003_rename_guide_id_rating_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='img',
            field=models.URLField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ratings', to='voyageherapi.guide'),
        ),
    ]
