# Generated by Django 4.2.2 on 2023-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageherapi', '0004_guide_img_alter_rating_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='img',
            field=models.URLField(default=None, null=True),
        ),
    ]
